export const animals = [
    "Cat", "Dog", "Lion", "Tiger", "Elephant", "Giraffe", "Zebra", "Rabbit", "Horse",
    "Sheep", "Goat", "Cow", "Pig", "Donkey", "Camel", "Llama", "Kangaroo", "Koala",
    "Panda", "Bear", "Wolf", "Fox", "Deer", "Moose", "Hippopotamus", "Rhinoceros",
    "Squirrel", "Mouse", "Rat", "Bat", "Otter", "Beaver", "Armadillo", "Sloth",
    "Porcupine", "Hedgehog", "Platypus", "Weasel", "Skunk", "Badger", "Chipmunk",
    "Wombat", "Cheetah", "Leopard", "Jaguar", "Antelope", "Bison", "Buffalo", "Gazelle",
    "Orangutan", "Chimpanzee", "Gorilla", "Baboon", "Lemur", "Mole", "Meerkat", "Hyena",
    "Eagle", "Hawk", "Falcon", "Owl", "Sparrow", "Seagull", "Crow", "Raven", "Parrot",
    "Macaw", "Cockatoo", "Penguin", "Pelican", "Flamingo", "Heron", "Stork", "Peacock",
    "Swan", "Duck", "Goose", "Turkey", "Vulture", "Woodpecker", "Hummingbird", "Kingfisher",
    "Canary", "Finch", "Robin", "Bluejay", "Cardinal", "Pigeon", "Dove", "Quail",
    "Ostrich", "Emu", "Kiwi", "Albatross", "Toucan", "Magpie", "Starling", "Budgerigar",
    "Snake", "Crocodile", "Alligator", "Lizard", "Gecko", "Iguana", "Chameleon",
    "Komodo Dragon", "Turtle", "Tortoise", "Monitor Lizard", "Garter Snake", "Python",
    "Boa Constrictor", "Cobra", "Rattlesnake", "Anaconda", "Sea Snake",
    "Frog", "Toad", "Newt", "Salamander", "Axolotl", "Shark", "Dolphin", "Whale", "Tuna", "Salmon", "Trout", "Eel", "Seahorse", "Clownfish", "Swordfish", "Marlin", "Catfish", "Piranha", "Angelfish", "Goldfish",
    "Betta Fish", "Barracuda", "Carp", "Stingray", "Manta Ray", "Herring", "Anchovy",
    "Cod", "Haddock", "Halibut", "Bass", "Grouper", "Snapper", "Ant", "Bee", "Wasp", "Hornet", "Butterfly", "Moth", "Dragonfly", "Damselfly", "Grasshopper", "Cricket", "Beetle", "Ladybug", "Firefly", "Spider", "Scorpion",
    "Tick", "Flea", "Centipede", "Millipede", "Cockroach", "Termite", "Mosquito",
    "Caterpillar", "Snail", "Slug", "Earthworm", "Jellyfish", "Octopus", "Squid",
    "Crab", "Lobster", "Shrimp", "Krill", "Clam", "Oyster", "Starfish", "Sea Urchin",
    "Sea Cucumber", "Blue Whale", "Humpback Whale", "Orca", "Beluga", "Narwhal", "Seal", "Sea Lion",
    "Walrus", "Manatee", "Dugong", "Axolotl", "Okapi", "Aardvark", "Pangolin", "Tasmanian Devil", "Quokka",
    "Cassowary", "Capybara", "Kakapo", "Saola", "Markhor", "Dragon", "Unicorn", "Phoenix", "Griffin", "Mermaid", "Hippogriff", "Kraken", "Yeti"
];
