spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social-media-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


logging:
  level:
    org:
      hibernate:
        SQL: debug

grpc:
  client:
    media-grpc:
      address: 'static://localhost:9050'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

