server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: blog-api
          uri: http://blog-api:8090
          predicates:
            - Path=/**


logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true



