server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - http://localhost:5173
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        - id: blog-api
          uri: http://blog-api:8090
          predicates:
            - Path=/blog/**
          filters:
            - RewritePath=/blog/(?<segment>.*), /$\{segment}
        - id: social-media-api
          uri: http://social-media-api:8080
          predicates:
            - Path=/social-media/**
          filters:
            - RewritePath=/social-media/(?<segment>.*), /$\{segment}
        - id: profile-api
          uri: http://profile-api:8080
          predicates:
            - Path=/prof/**
          filters:
            - RewritePath=/prof/(?<segment>.*), /$\{segment}

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
