server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: blog-api
          uri: http://blog-api:8090
          predicates:
            - Path=/blog/**
          filters:
            - RewritePath=/blog/(?<segment>.*), /$\{segment}
        - id: social-media-api
          uri: http://social-media-api:8080
          predicates:
            - Path=/social-media/**
          filters:
            - RewritePath=/social-media/(?<segment>.*), /$\{segment}
        - id: profile-api
          uri: http://profile-api:9040
          predicates:
            - Path=/profile/**
          filters:
            - RewritePath=/profile/(?<segment>.*), /$\{segment}

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
